# Generated by Django 4.0.4 on 2022-06-21 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='teachers',
            field=models.ManyToManyField(to='usersApp.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='comment_traité',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarite', models.CharField(blank=True, choices=[('P', 'P'), ('N', 'N'), ('NE', 'NE')], max_length=2)),
                ('attitude', models.CharField(blank=True, choices=[('P', 'P'), ('N', 'N'), ('NE', 'NE')], max_length=2)),
                ('attente', models.CharField(blank=True, choices=[('P', 'P'), ('N', 'N'), ('NE', 'NE')], max_length=2)),
                ('util', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('intr', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('accompl', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('cout', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('pres', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('cont', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('des', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('gen', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('comm', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('str', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('anx', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('col', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('enn', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('meco', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('confusion', models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.comment')),
            ],
        ),
    ]
