# Generated by Django 4.0.4 on 2022-06-22 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_module_teachers_alter_student_user_comment_traité'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_traité',
            old_name='accompl',
            new_name='Accomplissement',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='anx',
            new_name='Anxiété',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='attente',
            new_name='Attente',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='attitude',
            new_name='Attitude',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='col',
            new_name='Colère',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='comm',
            new_name='Communication',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='confusion',
            new_name='Confusion',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='cont',
            new_name='Contenu',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='cout',
            new_name='Cout',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='des',
            new_name='Design',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='enn',
            new_name='Ennui',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='gen',
            new_name='Gratitude',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='intr',
            new_name='Général',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='meco',
            new_name='Intrinsèque',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='pres',
            new_name='Joie',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='str',
            new_name='Mécontentement',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='polarite',
            new_name='Polarité',
        ),
        migrations.RenameField(
            model_name='comment_traité',
            old_name='util',
            new_name='Présentation',
        ),
        migrations.AddField(
            model_name='comment_traité',
            name='Commentaire',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='comment_traité',
            name='Module',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='comment_traité',
            name='Satisfaction',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0),
        ),
        migrations.AddField(
            model_name='comment_traité',
            name='Structure',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0),
        ),
        migrations.AddField(
            model_name='comment_traité',
            name='Séance',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment_traité',
            name='Utilité',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (0, '0')], default=0),
        ),
    ]
