# Generated by Django 4.0.4 on 2022-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_rename_module_comment_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='titre',
            field=models.TextField(max_length=100),
        ),
    ]
