# Generated by Django 4.0.4 on 2022-06-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0005_alter_module_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_traité',
            name='Attitude',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('H', 'H'), ('NE', 'NE')], max_length=2),
        ),
    ]
